#!/bin/bash

echo "criando diretorios"

mkdir /publico
mkdir /adm
mkdir /ven
mkdir /sec

echo "criando grupos de usuarios"

groupadd GRP_ADM
groupadd GRP_VEN
groupadd GRP_SEC

echo "adicionando usuarios aos grupos"

usermod -a -G GRP_ADM karlos
usermod -a -G GRP_ADM maria
usermod -a -G GRP_ADM joao

usermod -a -G GRP_ADM debora
usermod -a -G GRP_ADM sebastiana
usermod -a -G GRP_ADM roberto

usermod -a -G GRP_ADM josefina
usermod -a -G GRP_ADM amanda
usermod -a -G GRP_ADM rogerio

echo "especificando permissoes dos diretorios"

chown root:GRP_ADM /adm
chown root:GRP_VEN /ven
chown root:GRP_SEC /sec

chmod 770 /adm
chmod 770 /ven
chmod 770 /sec
chmod 777 /publico

echo "fim..."
